
script: |
            git config --global --add safe.directory /home/ubuntu/piplineIQ
            cd /home/ubuntu/piplineIQ
            git pull origin main
            pip3 install -r requirements.txt
            sudo systemctl restart django
            echo "App restarted!"
